# Generated by Django 3.2.3 on 2025-05-30 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_auto_20250530_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.market'),
        ),
    ]
