# Generated by Django 3.2.3 on 2025-05-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_alter_category_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='market',
            name='title',
            field=models.CharField(default='hello', max_length=255),
        ),
    ]
