# Generated by Django 3.2.3 on 2025-05-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_auto_20250530_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='market',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
