# Generated by Django 3.2.3 on 2025-05-29 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_frequentquestion_homepagewords_supportstaffdetails_testimonies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featureName', models.CharField(max_length=254)),
                ('featureIcon', models.CharField(max_length=254)),
            ],
        ),
    ]
